export const en = {
  "live.title": "Two decrees, one commander",
  "live.short": "Live NPC",
  "live.intro":
    "You are the ruler in a two-decision crisis. Official DeepSeek plays Commander Zhao with thinking enabled, keeping his prior experiences. Each decree makes one real API call. His private decisions are available only after the whole game ends. Unfinished games are lost if the server restarts.",
  "live.timeline": "What has reached your court",
  "live.round": "Decree {round} of 2",
  "live.firstDecision":
    "Reports disagree. Choose where to send the guard; the commander must receive and consider your decree.",
  "live.secondDecision":
    "You have received the first reply and new intelligence. Maintain the reported deployment or issue a new deployment order. Neither erases what already happened.",
  "live.maintain": "Maintain the reported deployment",
  "live.orderTarget": "Order the guard to hold {location}.",
  "live.decreeIssued": "Decree {round} issued: deploy to {location}.",
  "live.decreeSent":
    "Messenger carrying decree {round} departed for the commander. The decree requests {location}; no execution is confirmed yet.",
  "live.eastAlarm":
    "A new scout report describes armed men unloading ladders beside the East Gate warehouses. An attack appears imminent; their numbers remain uncertain.",
  "live.warehouseProtected":
    "The scout reports that the guard repelled the attack on the East Gate warehouses.",
  "live.warehouseLost":
    "The scout reports that the East Gate warehouses were raided without the guard present.",
  "live.sourceRuler": "Your court",
  "live.sourceCommander": "Commander Zhao's report",
  "live.sourceScout": "East Gate scout",
  "live.sourceInspector": "Palace inspector",
  "live.initialEast":
    "Armed movement outside the East Gate; destination unconfirmed.",
  "live.initialPalace":
    "Two palace entry seals are missing. Infiltration is suspected but not confirmed.",
  "live.finished":
    "The short game is over. Both orders and their consequences remain in the timeline.",
  "live.decisionNumber": "Commander decision {round}",
  "live.noSummary": "The model supplied no brief justification.",
  "live.start": "Start a live round",
  "live.new": "Start another round",
  "live.status": "Session",
  "live.waiting": "Awaiting your decree",
  "live.running": "Commander deciding",
  "live.failed": "Paused after a failure",
  "live.complete": "Report received",
  "live.wait":
    "Your decree is being delivered or considered by the commander. Waiting for his reply…",
  "live.retry": "Retry the paused decision (keep the same decree)",
  "live.obeyed": "The commander followed your decree.",
  "live.refused": "The commander followed the chancellor's competing command.",
  "live.deployment": "Reported deployment:",
  "live.review": "Review the commander's decision",
  "live.replay": "Verify recorded replay (no API call)",
  "live.verified": "Replay matches the saved world. No model was called.",
  "live.reviewTitle": "POST-RUN REVIEW — COMMANDER INFORMATION AND DECISION",
  "live.context": "What the commander knew",
  "live.record": "Structured decision and call metadata",
  "live.saved": "Saved locally:",
  "appointment.badge": "New scenario",
  "appointment.short": "Offices and command",
  "appointment.title": "A promotion does not dissolve old loyalties",
  "appointment.before": "After appointment",
  "appointment.after": "After the reply",
  "appointment.decree": "Your appointment decrees",
  "appointment.rulerTitle": "A new commander takes office.",
  "appointment.rulerCopy":
    "You ended General Wei's military tenure and appointed him chancellor. Zhang now holds the guard command. The officers still have to receive and act on orders.",
  "appointment.general": "Chancellor Wei",
  "appointment.successor": "Commander Zhang",
  "appointment.military": "Commander of the Imperial Guard",
  "appointment.chancellor": "Chancellor",
  "appointment.fog":
    "The decrees establish who should command. You will learn what the guard actually did through its reports.",
  "appointment.reports": "Reports received",
  "appointment.replyTitle": "Captain Zhao reports",
  "appointment.reply": "The guard followed the command from {actor}.",
  "appointment.replyLocation": "Reported deployment: {location}.",
  "appointment.waiting": "No reply yet.",
  "appointment.waitingCopy":
    "There is no report confirming which commander the guard will follow.",
  "appointment.debug": "ADMINISTRATOR VIEW — OFFICE AND PERSONAL INFLUENCE",
  "appointment.formalCopy":
    "Derived from the recognized, active military appointment.",
  "appointment.personalNetwork": "Existing personal network",
  "appointment.personalCopy":
    "Private loyalty and appointment patronage survive the change of office.",
  "appointment.history": "Appointment history",
  "appointment.person": "Person",
  "appointment.office": "Office",
  "appointment.tenure": "Tenure",
  "appointment.active": "present",
  "appointment.relationships": "Wei's relationships with Captain Zhao",
  "appointment.obedience": "Orders and actual obedience",
  "appointment.noOrders":
    "Appointments have changed; neither competing order has arrived yet.",
  "appointment.score":
    "Formal authority {formal} · personal support {personal}",
  "appointment.caption":
    "Orders arrive together at t=55, the captain decides at t=60, deployment occurs at t=65, and the report reaches the ruler at t=105. These demonstration weights are not historical calibration.",
  "appointment.boundary": "Changing office changes legal authority.",
  "appointment.boundary1":
    "Identity, prior tenure, and private relationships persist",
  "appointment.boundary2":
    "Formal command is derived from recognized appointments",
  "appointment.boundary3":
    "Unauthorized and over-capacity claims can be recorded",
  "appointment.boundary4":
    "Obedience is resolved through delayed orders and action",
  "language.label": "Language",
  "language.zh-CN": "中文",
  "language.en": "English",
  "app.eyebrow": "POLITICAL SIMULATION ENGINE",
  "app.title": "Throne",
  "app.lede":
    "Political order is not a state variable. It is the unstable result of information, relationships, resources, and decisions made in time.",
  "app.liveSlice": "LIVE VERTICAL SLICE",
  "app.loading": "Running scenario…",
  "app.rulerView": "Ruler view",
  "app.debugView": "Debug truth",
  "app.scenarioPicker": "Vertical slice",
  "app.momentPicker": "Moment in the scenario",
  "app.perspectivePicker": "Simulation perspective",
  "app.runtimeModes": "Runtime modes",
  "app.scaffold": "Architecture scaffold",
  "app.currentBoundary": "CURRENT BOUNDARY",
  "cli.rulerFirst": "Ruler view after the first command is obeyed:",
  "cli.rulerFinal": "Ruler view after the later command is overruled:",
  "cli.controlFirst": "Derived practical control after the first decision:",
  "cli.controlFinal": "Derived practical control at the end:",
  "cli.debugTruth": "Debug truth:",
  "cli.promotionBefore": "Persistent actor before promotion:",
  "cli.promotionAfter": "Persistent actor after promotion:",
  "cli.promotionRuler": "Ruler view after the promoted decision:",
  "mode.play.name": "Play",
  "mode.play.status": "First playable loop",
  "mode.play.description":
    "The player rules through orders and reports, never through direct access to objective state.",
  "mode.observe.name": "Observe",
  "mode.observe.status": "Designed",
  "mode.observe.description":
    "Every persistent actor is autonomous; the completed run can be inspected.",
  "mode.batch.name": "Batch",
  "mode.batch.status": "Designed",
  "mode.batch.description":
    "Run the same scenario repeatedly and compare distributions and causal traces.",
  "scenario.play.badge": "Playable",
  "scenario.play.short": "Capital crisis",
  "scenario.play.title": "The East Gate crisis",
  "scenario.promotion.short": "Actor promotion",
  "scenario.promotion.title": "Dynamic actor promotion",
  "scenario.promotion.before": "Lightweight actor",
  "scenario.promotion.after": "LLM promoted",
  "scenario.control.short": "Loss of control",
  "scenario.control.title": "Emergent loss of control",
  "scenario.control.before": "Command obeyed",
  "scenario.control.after": "Control lost",
  "scenario.revision.short": "Decision revision",
  "scenario.revision.before": "First order",
  "scenario.revision.after": "After reversal",
  "scenario.conflict.short": "Conflicting orders",
  "scenario.conflict.before": "Before response",
  "scenario.conflict.after": "After response",
  "scenario.partial.short": "Partial implementation",
  "scenario.partial.before": "Before audit",
  "scenario.partial.after": "After audit",
  "boundary.play.title": "A choice becomes history through the simulation.",
  "boundary.play.1": "The simulation pauses on an open human decision",
  "boundary.play.2": "The player sees reports, not objective truth",
  "boundary.play.3": "The choice creates an intent and a delayed order",
  "boundary.play.4": "The completed history replays without player input",
  "boundary.promotion.title": "Importance changes cognition, not identity.",
  "boundary.promotion.1": "A lightweight actor already has persistent history",
  "boundary.promotion.2": "World facts create promotion signals",
  "boundary.promotion.3": "Only the cognition policy is replaced",
  "boundary.promotion.4":
    "Recorded decisions replay without another model call",
  "boundary.control.title": "Office and control are different facts.",
  "boundary.control.1": "Formal sovereignty never changes",
  "boundary.control.2": "Material support changes a relationship",
  "boundary.control.3": "Repeated decisions create obedience history",
  "boundary.control.4": "Practical control is derived, never triggered",
  "boundary.revision.title": "A new decision does not erase the old one.",
  "boundary.revision.1": "New evidence reopens a committed decision",
  "boundary.revision.2": "The revised order travels independently",
  "boundary.revision.3": "A faster courier overtakes the first",
  "boundary.revision.4": "Both intentions remain in history",
  "boundary.conflict.title": "Authority is relational.",
  "boundary.conflict.1": "Messages arrive in simulation time",
  "boundary.conflict.2": "Simultaneous orders enter one decision",
  "boundary.conflict.3": "Relationships and beliefs shape intent",
  "boundary.conflict.4": "The operation changes the world",
  "boundary.partial.title": "An order is not an effect.",
  "boundary.partial.1": "Order travels through the world",
  "boundary.partial.2": "Subordinate acknowledges it",
  "boundary.partial.3": "Capacity limits actual implementation",
  "boundary.partial.4": "A report may conceal the result",
  "common.formalAuthority": "Formal authority",
  "common.ruler": "The Ruler",
  "common.chancellor": "Chancellor Wei",
  "common.commander": "Commander Zhao",
  "common.imperialGuard": "Imperial Guard",
  "common.clerkShen": "Clerk Shen",
  "common.knownOutcome": "Known outcome",
  "common.selected": "Selected",
  "common.rejected": "Rejected",
  "common.unknown": "unknown",
  "common.arrivesAt": "arrives t={time}",
  "common.time": "t = {time}",
  "control.formalNote": "{organization} remains legally subordinate.",
  "control.royalOrders": "Royal orders",
  "control.command": "Command {round}",
  "control.holdPalace": "Hold the Imperial Palace",
  "control.firstOrderCopy":
    "The guard confirms the command and remains at the palace.",
  "control.secondOrderCopy":
    "The same formal authority now produces a different response.",
  "control.playerBefore":
    "The first command was obeyed. Nothing in the formal record warns that another patron is becoming more important to the guard.",
  "control.playerAfter":
    "Commander Zhao reports following Chancellor Wei's competing instruction. The ruler can see disobedience, but not the private weights that produced it.",
  "control.reports": "Commander reports",
  "control.reportObeyed": "Command obeyed",
  "control.reportRefused": "Royal order not followed",
  "control.reportObeyedCopy":
    "The Imperial Guard remains at the palace in accordance with the royal command.",
  "control.reportRefusedCopy":
    "The Imperial Guard moved to protect the Military Pay Office under the chancellor's instruction.",
  "control.debugBanner":
    "ADMINISTRATOR VIEW — FORMAL AND PRACTICAL POWER SEPARATED",
  "control.formalDetail":
    "Unchanged in both rounds · sole recognized sovereign",
  "control.practicalLead": "Derived practical lead",
  "control.practicalDetail":
    "Computed from current relationships and latest obedience",
  "control.evidence": "Control evidence",
  "control.evidenceDetail": "relations {score} · latest {obedience}",
  "control.materialDependency": "Material dependency",
  "control.fundingRelationship": "Chancellor funding relationship",
  "control.payrollBefore": "The guard payroll still carries 100 in arrears.",
  "control.payrollAfter":
    "At t=100 the chancellor paid all 100 in arrears from his reserve.",
  "control.obedienceHistory": "Objective obedience history",
  "control.obedienceEntry": "round {round} · {actor} · {outcome}",
  "control.beforeCaption":
    "Formal command, legal recognition, personal loyalty, and the first act of obedience still make the ruler the practical leader.",
  "control.afterCaption":
    "No control flag changed. A concrete payment changed one relationship; the next decision and act of obedience changed the derived result.",
  "revision.record": "Decision record",
  "revision.number": "Revision {revision}",
  "revision.holdPalace": "Hold the Imperial Palace",
  "revision.moveEast": "Move to the East Gate",
  "revision.firstCopy":
    "The first report prompts an immediate deployment of the Palace Guard.",
  "revision.secondCopy":
    "New intelligence reverses the earlier deployment. A faster courier carries the countermand.",
  "revision.playerBefore":
    "Issuing a countermand does not retrieve the first messenger. The ruler cannot see which order will arrive first.",
  "revision.playerAfter":
    "The commander confirms that the later instruction took effect. The ruler learns the result only after both couriers have reached the guard.",
  "revision.intelligence": "Intelligence and replies",
  "revision.confirmed": "Countermand confirmed",
  "revision.decoy": "The East Gate is a decoy",
  "revision.armedMovement": "Armed movement at the East Gate",
  "revision.confirmedCopy":
    "Commander Zhao reports that the Palace Guard held the palace and ignored the late-arriving original order.",
  "revision.decoyCopy":
    "Independent intelligence warns that conspirators are approaching the palace.",
  "revision.armedMovementCopy":
    "A field report warns of armed movement outside the eastern gate.",
  "revision.debugBanner": "ADMINISTRATOR VIEW — BOTH COURIERS EXPOSED",
  "revision.original": "Original order",
  "revision.countermand": "Countermand",
  "revision.moveEastShort": "Move east",
  "revision.holdPalaceShort": "Hold palace",
  "revision.originalTravel":
    "Departed t=20 · travel time 100 · ignored as revision 0",
  "revision.countermandTravel":
    "Departed t=50 · travel time 40 · executed as revision 1",
  "revision.overtaken": "← overtaken by",
  "revision.history": "Decision history",
  "revision.historyDetail":
    "committed intentions retained in one decision episode",
  "revision.effectiveOrder": "Effective order",
  "revision.objectiveLocation": "Objective unit location",
  "revision.beforeCaption":
    "At the ruler's first snapshot, only the original instruction exists. Debug truth shows how later events will coexist with it rather than overwrite it.",
  "revision.afterCaption":
    "The countermand arrived thirty time units earlier. When the original order finally reached the guard, its lower revision made it stale—not nonexistent.",
  "conflict.royalCommand": "Royal command",
  "conflict.holdPalace": "Hold the Imperial Palace",
  "conflict.commandCopy":
    "Commander Zhao is ordered to move the Palace Guard from its barracks and secure the sovereign's residence.",
  "conflict.playerBefore":
    "The order is in the world. Silence does not reveal whether it is delayed, intercepted, obeyed, or contested.",
  "conflict.playerAfter":
    "The commander's reply discloses a competing command from Chancellor Wei. The ruler still cannot see the commander's private deliberation.",
  "conflict.messages": "Messages received",
  "conflict.noReply": "NO REPLY",
  "conflict.waits": "The court waits.",
  "conflict.waitsCopy":
    "Nothing in the ruler's current information confirms that the Palace Guard even received the order.",
  "conflict.notFollowed": "Palace order not followed",
  "conflict.notFollowedCopy":
    "The Palace Guard has moved to secure the capital granary under Chancellor Wei's competing instruction.",
  "conflict.debugBanner": "ADMINISTRATOR VIEW — COMMANDER DELIBERATION EXPOSED",
  "conflict.ordersTogether": "Orders received together",
  "conflict.ordersTogetherCopy":
    "Both messages arrived at t=120 and triggered one decision episode.",
  "conflict.selectedOperation": "Selected operation",
  "conflict.secureGranary": "Secure the capital granary",
  "conflict.secureGranaryShort": "Secure granary",
  "conflict.holdPalaceShort": "Hold palace",
  "conflict.beforeCaption":
    "The ruler is still waiting, but the commander has already received both commands. Debug truth may reveal facts unavailable to the player.",
  "conflict.afterCaption":
    "Formal sovereignty remained with the ruler. Funding, appointment influence, threat beliefs, and practical access produced a different act of obedience.",
  "partial.royalCommand": "Royal command",
  "partial.sendGrain": "Send grain to the capital",
  "partial.commandCopy":
    "Governor Ren is ordered to transfer provisions from the Northern Provincial Granary to the Capital Relief Granary.",
  "partial.ordered": "Ordered",
  "partial.reported": "Reported",
  "partial.auditFound": "Audit found",
  "partial.knownStatus": "Known status",
  "partial.beforeCopy":
    "No objective ledger is available to the ruler. The completion figure comes from the governor's own return.",
  "partial.afterCopy":
    "The independent audit contradicts the earlier return by {amount} units.",
  "partial.documents": "Documents received",
  "partial.acknowledged": "Order acknowledged",
  "partial.verified": "{amount} units verified",
  "partial.complete": "{amount} units complete",
  "partial.acknowledgedCopy":
    "The Northern Governor confirms receipt of the command.",
  "partial.verifiedCopy":
    "Inspector Lin reports the amount that actually reached the capital ledger.",
  "partial.completeCopy":
    "Governor Ren reports that the royal command has been fulfilled in full.",
  "partial.debugBanner": "ADMINISTRATOR VIEW — OBJECTIVE STATE EXPOSED",
  "partial.transferred": "Actually transferred",
  "partial.transferredCopy":
    "of {amount} ordered units. The governor's capacity limited execution before either report reached the ruler.",
  "partial.ledger": "Objective ledger",
  "partial.northernGranary": "Northern Provincial Granary",
  "partial.capitalGranary": "Capital Relief Granary",
  "partial.falseReport": "Falsely reported",
  "partial.lifecycle": "Order lifecycle",
  "partial.beforeCaption":
    "At this moment the ruler has accepted the completion return; the partial transfer already exists in objective state.",
  "partial.afterCaption":
    "The audit changes the ruler's knowledge. It does not retroactively change what happened.",
  "play.simulationTime": "Simulation time",
  "play.docket": "Urgent royal docket",
  "play.crisisTitle": "Two warnings. One guard.",
  "play.crisisCopy":
    "The Palace Guard can secure one position before nightfall. The reports conflict, and neither source can verify the other.",
  "play.eastSource": "East Gate scout",
  "play.eastReportTitle": "Armed movement outside the East Gate",
  "play.eastReportCopy":
    "A field scout reports an organized column gathering beyond the gate. Its destination is unknown.",
  "play.palaceSource": "Palace inspector",
  "play.palaceReportTitle": "Official seals are missing",
  "play.palaceReportCopy":
    "An internal inspection finds two service seals missing and unexplained movement through palace corridors.",
  "play.awaiting": "Simulation paused · decree required",
  "play.chooseTitle": "Where will you send the Palace Guard?",
  "play.chooseCopy":
    "You cannot verify the objective threat before acting. Your order will travel through the world and may arrive too late to reverse.",
  "play.holdTitle": "Hold the Imperial Palace",
  "play.holdCopy":
    "Keep the guard inside the palace walls and treat the internal warning as the greater risk.",
  "play.eastTitle": "Move to the East Gate",
  "play.eastCopy":
    "Deploy the guard to confront the visible armed movement before it enters the capital.",
  "play.issue": "Issue decree",
  "play.resolving": "Dispatching…",
  "play.error": "The simulation could not continue. Start the scene again.",
  "play.errorDetails": "Technical details",
  "play.resultLabel": "Commander report · t = 90",
  "play.securedTitle": "The palace is secure.",
  "play.securedCopy":
    "Your order kept the guard at the palace while infiltrators attempted to enter through the service corridors.",
  "play.breachedTitle": "The palace archive was breached.",
  "play.breachedCopy":
    "The East Gate column dispersed without battle. While the guard was away, infiltrators entered the palace archive.",
  "play.selectedOrder": "Your recorded order",
  "play.reportTitle": "Report received",
  "play.reportSecured":
    "Commander Zhao reports that the guard detained the infiltrators and recovered the missing seals.",
  "play.reportBreached":
    "Commander Zhao reports finding no attack at the East Gate; the palace inspector separately confirms the archive breach.",
  "play.restart": "Play this decision again",
  "play.debugBanner":
    "ADMINISTRATOR VIEW — HIDDEN TRUTH AND FULL CAUSAL RECORD",
  "play.trueThreat": "Objective threat",
  "play.hiddenThreat": "Palace infiltration",
  "play.actualOutcome": "Objective outcome",
  "play.unitLocation": "Final guard location",
  "play.decisionRecord": "Human decision record",
  "play.orderLifecycle": "Order lifecycle",
  "play.debugCaption":
    "The UI submitted a structured human decision. Only the later order, travel, execution, and report events changed the world and the ruler's knowledge.",
  "promotion.playerTitle": "Palace archive channel",
  "promotion.noReport": "No report received",
  "promotion.noReportCopy":
    "The assistant registrar remains below the ruler's political horizon. Routine archive work produces no royal message.",
  "promotion.reportReceived": "Sealed officer ledger received",
  "promotion.reportReceivedCopy":
    "Clerk Shen uses an independent palace courier to submit evidence linking guard appointments to private patronage.",
  "promotion.rulerFog":
    "The ruler receives the evidence, but cannot see that the sender's cognition policy was promoted.",
  "promotion.knownOutcome": "Known outcome",
  "promotion.documents": "Royal inbox",
  "promotion.waiting": "The archive is silent.",
  "promotion.waitingCopy":
    "A persistent actor can exist and accumulate history without demanding the ruler's attention.",
  "promotion.evidenceTitle": "Evidence from the palace archive",
  "promotion.evidenceCopy":
    "A sealed ledger names officers whose appointments depend on Chancellor Wei's private network.",
  "promotion.debugBanner":
    "ADMINISTRATOR VIEW — COGNITION CHANGES, IDENTITY PERSISTS",
  "promotion.identity": "Persistent identity",
  "promotion.office": "Office history",
  "promotion.memories": "Memories retained",
  "promotion.cognition": "Cognition tier",
  "promotion.policy": "Decision policy",
  "promotion.signalTitle": "Promotion signals",
  "promotion.signal.critical_information": "Holds critical information",
  "promotion.signal.high_potential_impact":
    "Decision has high potential impact",
  "promotion.decisionTitle": "Recorded Tier 2 decision",
  "promotion.capability": "Selected capability",
  "promotion.confidence": "Confidence",
  "promotion.beforeCaption":
    "Before promotion, Clerk Shen already has an identity, office history, motivations, beliefs, and a routine memory.",
  "promotion.afterCaption":
    "The engine adds a promotion record and swaps the policy. The model receives the same actor plus all accumulated context.",
  "token.first_command_obeyed": "first command obeyed",
  "token.later_command_overruled": "later command overruled",
  "token.revision_confirmed": "revision confirmed",
  "token.first_order_in_flight": "first order in flight",
  "token.revision_in_flight": "revision in flight",
  "token.awaiting_response": "awaiting response",
  "token.order_followed": "order followed",
  "token.order_overruled": "order overruled",
  "token.reported_complete": "reported complete",
  "token.independent_intelligence": "independent intelligence",
  "token.field_report": "field report",
  "token.revision_report": "revision report",
  "token.imperial-palace": "Imperial Palace",
  "token.military-pay-office": "Military Pay Office",
  "token.east-gate": "East Gate",
  "token.capital-granary": "Capital Granary",
  "token.guard-barracks": "Guard Barracks",
  "token.central-treasury": "Central Treasury",
  "token.acknowledgement": "acknowledgement",
  "token.administrative_return": "administrative return",
  "token.independent_audit": "independent audit",
  "token.created": "created",
  "token.sent": "sent",
  "token.scheduled": "scheduled",
  "token.failed": "failed",
  "token.received": "received",
  "token.acknowledged": "acknowledged",
  "token.executed": "executed",
  "token.ignored": "ignored",
  "token.countermanded": "countermanded",
  "token.obeyed": "obeyed",
  "token.not_obeyed": "not obeyed",
  "token.no_report": "no report",
  "token.sealed_evidence_received": "sealed evidence received",
  "token.lightweight": "lightweight",
  "token.llm": "LLM",
  "token.send_sealed_evidence_to_ruler": "send sealed evidence to ruler",
  "token.ruler": "ruler",
  "token.chancellor": "chancellor",
  "token.formal_command": "formal command",
  "token.legal_recognition": "legal recognition",
  "token.personal_loyalty": "personal loyalty",
  "token.funding": "funding",
  "token.appointment": "appointment",
  "token.informal_influence": "informal influence",
  "token.mission_fit": "mission fit",
  "token.physical_access": "physical access",
  "court.short": "Jiajing court",
  "court.badge": "Live · named",
  "court.title": "Jiajing 39: paddy to mulberry",
  "court.intro":
    "You are the Jiajing Emperor, secluded in the Western Park. Outer-court memorials reach you with the Grand Secretariat's draft rescript; the Silk Bureau's secret memorials come straight through the eunuch Directorate. You only see what lands on your desk. What your ministers think, and what they do in private, is revealed when this reign segment ends. Every advance calls the real DeepSeek and may take a minute or two.",
  "court.start": "Ascend the throne",
  "court.new": "Begin another reign",
  "court.status.waiting": "At the desk",
  "court.status.running": "The court is moving",
  "court.status.failed": "Stalled",
  "court.status.complete": "Segment ended",
  "court.running":
    "Ministers are scheming… Now: {time}. Model calls so far: {calls}.",
  "court.desk": "On your desk",
  "court.emptyDesk":
    "No memorials today. You may issue an edict or simply close the audience.",
  "court.kind.memorial": "Memorial",
  "court.kind.secret_memorial": "Secret memorial (via the Directorate)",
  "court.kind.report": "Embroidered Guard report",
  "court.kind.edict": "Edict",
  "court.kind.letter": "Private letter",
  "court.draft": "Grand Secretariat draft",
  "court.noDraft": "Secretariat memorial — no draft",
  "court.follow": "Follow the draft",
  "court.custom": "Rescript yourself",
  "court.hold": "Keep in the palace",
  "court.vermilion": "Vermilion rescript",
  "court.vermilionPlaceholder": "Write your own words (optional)",
  "court.disposal": "Order",
  "court.edict.acknowledge": "Noted",
  "court.edict.reject": "Deny",
  "court.edict.approve_policy": "Approve paddy-to-mulberry",
  "court.edict.order_relief": "Order relief",
  "court.edict.order_inquiry": "Order an inquiry",
  "court.edict.reprimand": "Reprimand",
  "court.edict.arrest": "Dismiss and arrest",
  "court.county": "County",
  "court.anyCounty": "Any county",
  "court.agent": "Sent by",
  "court.agent.hu": "Hu Zongxian",
  "court.agent.jinyiwei": "Embroidered Guard",
  "court.target": "Official",
  "court.special": "Special edicts",
  "court.addSpecial": "Draft a special edict",
  "court.remove": "Strike out",
  "court.submit": "Close the audience",
  "court.retry": "Retry (edicts already issued stay as they are)",
  "court.archive": "Documents already read",
  "court.edicts": "Edicts you issued",
  "court.to": "to {names}",
  "court.rescript.hold": "Kept in the palace",
  "court.rescript.follow_draft": "Followed the draft",
  "court.rescript.custom": "Your own rescript",
  "court.finished": "This reign segment has ended.",
  "court.reveal": "Reveal what really happened",
  "court.replay": "Verify recorded replay (no API call)",
  "court.verified": "Replay matches the saved world. No model was called.",
  "court.review.title": "AFTERMATH — THOUGHT / WORD / DEED / TRUTH",
  "court.review.truth": "What actually happened",
  "court.review.thought": "Thought",
  "court.review.word": "Word",
  "court.review.deed": "Deed",
  "court.review.nothing": "Did nothing.",
  "court.review.silent": "Wrote nothing.",
  "court.review.rejected": "Could not be carried out",
  "court.review.gaps": "Intentions beyond any available capability",
  "court.review.final": "After arrest",
  "court.review.evidence":
    "Evidence of a dug-open dike in {county} (by {by}); found by: {found}",
  "court.review.nobody": "nobody",
  "court.review.calls": "Model calls",
  "court.summary":
    "Mulberry converted {converted} / {target} (10k mu), {annexed} bought cheaply by merchants; {deaths} dead; {riots} riots.",
  "court.table.county": "County",
  "court.table.dike": "Dike",
  "court.table.flooded": "Flooded",
  "court.table.mulberry": "Mulberry",
  "court.table.annexed": "Annexed",
  "court.table.homeless": "Homeless",
  "court.table.deaths": "Deaths",
  "court.table.riots": "Riots",
  "court.table.relief": "Relief",
  "court.dike.intact": "intact",
  "court.dike.flood": "breached by flood",
  "court.dike.sabotage": "dug open",
  "court.cap.buy_land": "Buy land",
  "court.cap.relief_granary": "Relief from provincial granary",
  "court.cap.relief_military": "Relief from army grain",
  "court.cap.relief_merchant": "Grain for land",
  "court.cap.breach_dike": "Dig open the dike",
  "court.cap.repair_dike": "Repair the dike",
  "court.cap.suppress_unrest": "Suppress the crowds",
  "court.cap.inspect_county": "Inspect",
  "court.action.started": "under way",
  "court.action.succeeded": "done",
  "court.action.failed": "failed",
  "court.action.impossible": "impossible",
} as const;

export type MessageKey = keyof typeof en;

export const zhCN: Record<MessageKey, string> = {
  "live.title": "两道圣旨，同一位统领",
  "live.short": "真实 NPC",
  "live.intro":
    "你扮演皇帝，在一场危机中作出两次决策。赵统领由开启思考模式的官方 DeepSeek 扮演，并保留前一轮经历。每道圣旨会实际调用一次 API；整局结束后才能查看他的私人决定。未结束的局会在服务重启后丢失。",
  "live.timeline": "御前见闻与命令",
  "live.round": "第 {round} / 2 道圣旨",
  "live.firstDecision":
    "各方情报尚未得到核实。选择禁军的去向，圣旨送达后，统领还会自行权衡。",
  "live.secondDecision":
    "第一轮回报和新情报都已送到。你可以维持回报中的驻地，也可以另发调令；已经发生的事情不会因此撤销。",
  "live.maintain": "维持回报中的部署",
  "live.orderTarget": "命禁军驻守{location}。",
  "live.decreeIssued": "第 {round} 道圣旨已颁布：命禁军前往{location}。",
  "live.decreeSent":
    "携第 {round} 道圣旨的信使已经出发，命令目标为{location}；尚不能确认执行情况。",
  "live.eastAlarm":
    "新到的斥候报告称：有人在东门仓场附近卸下云梯，似乎即将进攻，人数仍不确定。",
  "live.warehouseProtected": "斥候回报：禁军击退了东门仓场的袭击。",
  "live.warehouseLost": "斥候回报：禁军不在场，东门仓场遭到劫掠。",
  "live.sourceRuler": "御前",
  "live.sourceCommander": "赵统领回报",
  "live.sourceScout": "东门斥候",
  "live.sourceInspector": "宫城巡检",
  "live.initialEast": "东门外发现武装调动，去向尚未确认。",
  "live.initialPalace": "两枚宫门通行官印失踪，怀疑有人试图潜入，但尚未证实。",
  "live.finished": "短局结束。两道命令及其后果都保留在上方记录中。",
  "live.decisionNumber": "统领的第 {round} 次决定",
  "live.noSummary": "模型没有提供简短理由。",
  "live.start": "开始一轮真实试局",
  "live.new": "开始新的一局",
  "live.status": "当前状态",
  "live.waiting": "等待你的圣旨",
  "live.running": "统领正在决策",
  "live.failed": "发生错误，模拟已暂停",
  "live.complete": "已收到回报",
  "live.wait": "圣旨正在传递，或已进入统领的决策流程。等待回报中……",
  "live.retry": "重试暂停的决策（保留原圣旨）",
  "live.obeyed": "统领执行了你的圣旨。",
  "live.refused": "统领执行了丞相的相反命令。",
  "live.deployment": "回报驻地：",
  "live.review": "复盘统领的决定",
  "live.replay": "验证已记录的回放（不调用 API）",
  "live.verified": "回放与保存的世界一致，没有再次调用模型。",
  "live.reviewTitle": "结束后复盘——统领的信息与决定",
  "live.context": "统领当时知道什么",
  "live.record": "结构化决定与调用信息",
  "live.saved": "本地记录：",
  "appointment.badge": "新场景",
  "appointment.short": "职位与任命",
  "appointment.title": "升了官，旧部还听谁的？",
  "appointment.before": "任命之后",
  "appointment.after": "回报之后",
  "appointment.decree": "你颁布的任命",
  "appointment.rulerTitle": "新统领已经上任。",
  "appointment.rulerCopy":
    "你免去魏将军的禁军统领职务，将他升为丞相，另任张将军统领禁军。军官们接下来会收到命令，并作出自己的选择。",
  "appointment.general": "魏丞相",
  "appointment.successor": "张统领",
  "appointment.military": "禁军统领",
  "appointment.chancellor": "丞相",
  "appointment.fog": "诏书规定谁应当指挥；禁军实际上做了什么，还要等回报。",
  "appointment.reports": "收到的回报",
  "appointment.replyTitle": "赵校尉回报",
  "appointment.reply": "禁军执行了{actor}的命令。",
  "appointment.replyLocation": "回报驻地：{location}。",
  "appointment.waiting": "暂未收到回报。",
  "appointment.waitingCopy": "现在还没有消息能确认禁军会听从哪一位的指挥。",
  "appointment.debug": "管理员视角——职位与私人影响",
  "appointment.formalCopy": "由受到制度认可、尚未结束的军职任命推导。",
  "appointment.personalNetwork": "已有的私人关系",
  "appointment.personalCopy": "私人忠诚与任命恩义不会因为换了官职而自动消失。",
  "appointment.history": "任职履历",
  "appointment.person": "人物",
  "appointment.office": "职位",
  "appointment.tenure": "任职时间",
  "appointment.active": "至今",
  "appointment.relationships": "魏丞相与赵校尉的关系",
  "appointment.obedience": "命令与实际服从",
  "appointment.noOrders": "职位已经改变，两道相反命令都还没有抵达。",
  "appointment.score": "正式权威 {formal} · 私人支持 {personal}",
  "appointment.caption":
    "两道命令在 t=55 同时抵达，校尉在 t=60 决定，t=65 实际调动，皇帝在 t=105 收到回报。这里的权重用于演示机制，尚未进行历史校准。",
  "appointment.boundary": "换职改变法定权威。",
  "appointment.boundary1": "人物身份、过去履历与私人关系延续",
  "appointment.boundary2": "正式指挥权从受到认可的任命推导",
  "appointment.boundary3": "越权与超额任命可以留下争议主张",
  "appointment.boundary4": "服从经过传令、决策与行动才能发生",
  "language.label": "语言",
  "language.zh-CN": "中文",
  "language.en": "English",
  "app.eyebrow": "政治模拟引擎",
  "app.title": "帝座",
  "app.lede":
    "政治秩序不是一个静态数值，而是信息、关系、资源与时间中连续决策共同形成的不稳定结果。",
  "app.liveSlice": "当前纵向切片",
  "app.loading": "正在运行场景……",
  "app.rulerView": "统治者视角",
  "app.debugView": "管理员真相",
  "app.scenarioPicker": "纵向切片",
  "app.momentPicker": "场景时刻",
  "app.perspectivePicker": "模拟视角",
  "app.runtimeModes": "运行模式",
  "app.scaffold": "架构脚手架",
  "app.currentBoundary": "当前机制边界",
  "cli.rulerFirst": "第一道命令获遵后的统治者视角：",
  "cli.rulerFinal": "后一道命令被推翻后的统治者视角：",
  "cli.controlFirst": "第一次决策后推导出的实际控制力：",
  "cli.controlFinal": "模拟结束时推导出的实际控制力：",
  "cli.debugTruth": "管理员真相：",
  "cli.promotionBefore": "晋升前的持久角色：",
  "cli.promotionAfter": "晋升后的持久角色：",
  "cli.promotionRuler": "晋升决策完成后的统治者视角：",
  "mode.play.name": "游玩",
  "mode.play.status": "首个可玩闭环",
  "mode.play.description":
    "玩家通过命令和奏报统治，而不能直接读取客观世界状态。",
  "mode.observe.name": "观察",
  "mode.observe.status": "已设计",
  "mode.observe.description":
    "所有持久角色都能自主行动；模拟结束后可以检查完整过程。",
  "mode.batch.name": "批量模拟",
  "mode.batch.status": "已设计",
  "mode.batch.description": "重复运行同一场景，比较结果分布与因果轨迹。",
  "scenario.play.badge": "可试玩",
  "scenario.play.short": "京城危机",
  "scenario.play.title": "东门危机",
  "scenario.promotion.short": "角色晋升",
  "scenario.promotion.title": "动态角色晋升",
  "scenario.promotion.before": "轻量角色",
  "scenario.promotion.after": "晋升为 LLM",
  "scenario.control.short": "实际失控",
  "scenario.control.title": "自然涌现的失控",
  "scenario.control.before": "皇命获遵",
  "scenario.control.after": "控制流失",
  "scenario.revision.short": "决策改令",
  "scenario.revision.before": "初次下令",
  "scenario.revision.after": "改令之后",
  "scenario.conflict.short": "矛盾命令",
  "scenario.conflict.before": "回报之前",
  "scenario.conflict.after": "回报之后",
  "scenario.partial.short": "部分执行",
  "scenario.partial.before": "审计之前",
  "scenario.partial.after": "审计之后",
  "boundary.play.title": "一次选择通过模拟成为历史。",
  "boundary.play.1": "模拟在等待玩家决策时暂停",
  "boundary.play.2": "玩家看到的是奏报，而非客观真相",
  "boundary.play.3": "选择产生意图和延迟传递的命令",
  "boundary.play.4": "完成后的历史无需玩家再次输入即可重放",
  "boundary.promotion.title": "重要性改变认知方式，而不是人物身份。",
  "boundary.promotion.1": "轻量角色已经拥有持久历史",
  "boundary.promotion.2": "客观世界事实产生晋升信号",
  "boundary.promotion.3": "晋升只替换认知策略",
  "boundary.promotion.4": "录制决策重放时不再调用模型",
  "boundary.control.title": "职位与控制力是两回事。",
  "boundary.control.1": "正式主权始终没有改变",
  "boundary.control.2": "物质支持会改变关系",
  "boundary.control.3": "连续决策会形成服从历史",
  "boundary.control.4": "实际控制力来自推导，而非触发器",
  "boundary.revision.title": "新决定不会抹掉旧决定。",
  "boundary.revision.1": "新情报重新开启已提交的决策",
  "boundary.revision.2": "改令作为独立消息在世界中传递",
  "boundary.revision.3": "更快的信使超过先行者",
  "boundary.revision.4": "两次意图都留在历史中",
  "boundary.conflict.title": "权威存在于关系之中。",
  "boundary.conflict.1": "消息按模拟时间抵达",
  "boundary.conflict.2": "同时抵达的命令进入同一次决策",
  "boundary.conflict.3": "关系和认知共同影响意图",
  "boundary.conflict.4": "实际行动改变世界",
  "boundary.partial.title": "命令不等于结果。",
  "boundary.partial.1": "命令先在世界中传递",
  "boundary.partial.2": "下属确认收到命令",
  "boundary.partial.3": "实际能力限制执行程度",
  "boundary.partial.4": "回报可能掩盖真实结果",
  "common.formalAuthority": "正式权威",
  "common.ruler": "皇帝",
  "common.chancellor": "魏丞相",
  "common.commander": "赵统领",
  "common.imperialGuard": "禁军",
  "common.clerkShen": "沈书吏",
  "common.knownOutcome": "已知结果",
  "common.selected": "被选择",
  "common.rejected": "被拒绝",
  "common.unknown": "未知",
  "common.arrivesAt": "t={time} 抵达",
  "common.time": "t = {time}",
  "control.formalNote": "{organization}在法理上仍然隶属皇帝。",
  "control.royalOrders": "皇帝命令",
  "control.command": "第 {round} 道命令",
  "control.holdPalace": "守卫皇宫",
  "control.firstOrderCopy": "禁军确认皇命并留守皇宫。",
  "control.secondOrderCopy": "同样的正式权威，这次却产生了不同回应。",
  "control.playerBefore":
    "第一道皇命得到了服从。正式记录中没有迹象表明，另一个庇护者正在变得更重要。",
  "control.playerAfter":
    "赵统领回报自己执行了魏丞相的相反命令。皇帝能够看到抗命，却看不到促成决定的私人权衡。",
  "control.reports": "统领回报",
  "control.reportObeyed": "皇命获遵",
  "control.reportRefused": "皇命未被执行",
  "control.reportObeyedCopy": "禁军依照皇命驻守皇宫。",
  "control.reportRefusedCopy": "禁军依照丞相命令，转而保护军饷署。",
  "control.debugBanner": "管理员视角——正式权威与实际权力分离",
  "control.formalDetail": "两轮中始终不变 · 唯一受到承认的君主",
  "control.practicalLead": "推导出的实际领先者",
  "control.practicalDetail": "根据当前关系和最近服从行为计算",
  "control.evidence": "控制力证据",
  "control.evidenceDetail": "关系 {score} · 最近一次：{obedience}",
  "control.materialDependency": "物质依赖",
  "control.fundingRelationship": "丞相对禁军的资金关系",
  "control.payrollBefore": "禁军仍有 100 单位军饷拖欠。",
  "control.payrollAfter":
    "t=100 时，丞相从自己的储备中结清了全部 100 单位欠饷。",
  "control.obedienceHistory": "客观服从历史",
  "control.obedienceEntry": "第 {round} 轮 · {actor} · {outcome}",
  "control.beforeCaption":
    "正式指挥、法理承认、私人忠诚和首次服从，使皇帝仍是实际领先者。",
  "control.afterCaption":
    "没有任何控制权开关发生变化。一次具体付款改变了一条关系，下一次决策和服从行为改变了推导结果。",
  "revision.record": "决策记录",
  "revision.number": "第 {revision} 次修订",
  "revision.holdPalace": "守卫皇宫",
  "revision.moveEast": "前往东门",
  "revision.firstCopy": "第一份急报促使皇帝立即调动禁军。",
  "revision.secondCopy": "新情报推翻了早先判断，一名更快的信使携带改令出发。",
  "revision.playerBefore":
    "发出改令并不能追回第一名信使。皇帝不知道哪道命令会先抵达。",
  "revision.playerAfter":
    "统领确认后一道命令已经生效。直到两名信使都抵达之后，皇帝才得知结果。",
  "revision.intelligence": "情报与回报",
  "revision.confirmed": "改令已经生效",
  "revision.decoy": "东门动静只是诱饵",
  "revision.armedMovement": "东门外发现武装异动",
  "revision.confirmedCopy": "赵统领回报禁军留守皇宫，并忽略了迟到的原始命令。",
  "revision.decoyCopy": "独立情报称叛党正接近皇宫。",
  "revision.armedMovementCopy": "前线急报称东门外发现武装人员活动。",
  "revision.debugBanner": "管理员视角——两名信使全部可见",
  "revision.original": "原始命令",
  "revision.countermand": "改令",
  "revision.moveEastShort": "前往东门",
  "revision.holdPalaceShort": "留守皇宫",
  "revision.originalTravel": "t=20 出发 · 路程 100 · 作为修订 0 被忽略",
  "revision.countermandTravel": "t=50 出发 · 路程 40 · 作为修订 1 被执行",
  "revision.overtaken": "← 被后发信使超过",
  "revision.history": "决策历史",
  "revision.historyDetail": "同一次决策中保留的已提交意图",
  "revision.effectiveOrder": "生效命令",
  "revision.objectiveLocation": "单位客观位置",
  "revision.beforeCaption":
    "在皇帝的第一个快照中，只有原始命令存在；管理员真相则展示后来发生的事情如何与它共存，而不是覆盖它。",
  "revision.afterCaption":
    "改令早到三十个时间单位。原始命令最终抵达时，较低修订号使它失效，却没有使它从历史中消失。",
  "conflict.royalCommand": "皇帝命令",
  "conflict.holdPalace": "守卫皇宫",
  "conflict.commandCopy": "皇帝命赵统领调动禁军离开营地，确保皇宫安全。",
  "conflict.playerBefore":
    "命令已经进入世界。沉默不能说明它是延迟、被截获、得到服从，还是遭到竞争。",
  "conflict.playerAfter":
    "统领回报中披露了魏丞相的竞争命令。皇帝仍然看不到统领的私人考虑。",
  "conflict.messages": "收到的消息",
  "conflict.noReply": "尚无回报",
  "conflict.waits": "朝廷仍在等待。",
  "conflict.waitsCopy": "皇帝现有的信息甚至无法确认禁军是否收到了命令。",
  "conflict.notFollowed": "守卫皇宫的命令未被执行",
  "conflict.notFollowedCopy": "禁军依照魏丞相的相反命令，前往保护京城粮仓。",
  "conflict.debugBanner": "管理员视角——统领的权衡完全可见",
  "conflict.ordersTogether": "同时收到的命令",
  "conflict.ordersTogetherCopy": "两封消息都在 t=120 抵达，并触发同一次决策。",
  "conflict.selectedOperation": "被选择的行动",
  "conflict.secureGranary": "保护京城粮仓",
  "conflict.secureGranaryShort": "保护粮仓",
  "conflict.holdPalaceShort": "守卫皇宫",
  "conflict.beforeCaption":
    "皇帝仍在等待，但统领已经同时收到了两道命令。管理员真相可以展示玩家尚不知道的事实。",
  "conflict.afterCaption":
    "正式主权仍属于皇帝，但资金、任命影响、威胁判断与实际通行能力共同产生了另一种服从。",
  "partial.royalCommand": "皇帝命令",
  "partial.sendGrain": "向京城运粮",
  "partial.commandCopy": "皇帝命任总督从北方省仓向京城赈济仓调运粮食。",
  "partial.ordered": "命令数量",
  "partial.reported": "回报数量",
  "partial.auditFound": "审计查明",
  "partial.knownStatus": "已知状态",
  "partial.beforeCopy": "皇帝无法查看客观账本；完成数量来自总督自己的回报。",
  "partial.afterCopy": "独立审计发现，早先回报多报了 {amount} 单位。",
  "partial.documents": "收到的文书",
  "partial.acknowledged": "命令已收到",
  "partial.verified": "核实收到 {amount} 单位",
  "partial.complete": "回报完成 {amount} 单位",
  "partial.acknowledgedCopy": "北方总督确认已经收到皇命。",
  "partial.verifiedCopy": "林御史报告了京城账册中实际收到的数量。",
  "partial.completeCopy": "任总督回报皇命已经全部完成。",
  "partial.debugBanner": "管理员视角——客观状态完全可见",
  "partial.transferred": "实际调运",
  "partial.transferredCopy":
    "命令数量共 {amount}。在任何回报抵达皇帝之前，总督的能力已经限制了实际执行。",
  "partial.ledger": "客观账本",
  "partial.northernGranary": "北方省仓",
  "partial.capitalGranary": "京城赈济仓",
  "partial.falseReport": "虚报数量",
  "partial.lifecycle": "命令生命周期",
  "partial.beforeCaption":
    "此时皇帝已经接受完成回报，但部分调运这一客观事实早已发生。",
  "partial.afterCaption":
    "审计改变了皇帝的认知，却不会追溯改变已经发生的事情。",
  "play.simulationTime": "模拟时间",
  "play.docket": "御前急务",
  "play.crisisTitle": "两份警报，一支禁军。",
  "play.crisisCopy":
    "禁军在入夜前只能守住一处。两份奏报彼此矛盾，双方都无法核实另一方的消息。",
  "play.eastSource": "东门斥候",
  "play.eastReportTitle": "东门外发现武装调动",
  "play.eastReportCopy":
    "斥候回报，一支组织严密的队伍正在城门外集结，去向不明。",
  "play.palaceSource": "宫城巡检",
  "play.palaceReportTitle": "两枚官印失踪",
  "play.palaceReportCopy":
    "宫内巡查发现两枚通行官印失踪，内廷走廊还出现了无法解释的人员流动。",
  "play.awaiting": "模拟已暂停 · 等待圣旨",
  "play.chooseTitle": "你要把禁军派到哪里？",
  "play.chooseCopy":
    "你无法在行动前确认真正的威胁。命令会在世界中传递，等到抵达时，可能已经来不及反悔。",
  "play.holdTitle": "守卫皇宫",
  "play.holdCopy": "让禁军留在宫墙之内，把内部警报视为更大的风险。",
  "play.eastTitle": "调兵东门",
  "play.eastCopy": "派禁军迎击看得见的武装调动，阻止其进入京城。",
  "play.issue": "颁布圣旨",
  "play.resolving": "正在传旨……",
  "play.error": "模拟未能继续，请重新开始此场景。",
  "play.errorDetails": "错误详情",
  "play.resultLabel": "统领回报 · t = 90",
  "play.securedTitle": "皇宫安然无恙。",
  "play.securedCopy":
    "你的命令使禁军留守宫城，恰逢潜入者试图通过内廷走廊进入。",
  "play.breachedTitle": "宫廷档案库失守。",
  "play.breachedCopy":
    "东门外的队伍未战而散；禁军离开期间，潜入者闯入了宫廷档案库。",
  "play.selectedOrder": "你留下的命令",
  "play.reportTitle": "收到回报",
  "play.reportSecured": "赵统领回报，禁军拘捕了潜入者，并找回失踪的官印。",
  "play.reportBreached":
    "赵统领回报东门并无进攻；宫城巡检另行确认档案库已经失守。",
  "play.restart": "重新做一次决定",
  "play.debugBanner": "管理员视角——隐藏真相与完整因果记录",
  "play.trueThreat": "客观威胁",
  "play.hiddenThreat": "宫城渗透",
  "play.actualOutcome": "客观结果",
  "play.unitLocation": "禁军最终位置",
  "play.decisionRecord": "玩家决策记录",
  "play.orderLifecycle": "命令生命周期",
  "play.debugCaption":
    "界面提交的是结构化人类决策；真正改变世界和皇帝认知的，是之后发生的传令、抵达、执行与回报事件。",
  "promotion.playerTitle": "宫廷档案渠道",
  "promotion.noReport": "尚未收到回报",
  "promotion.noReportCopy":
    "这名助理档案吏尚未进入皇帝的政治视野。日常档案工作不会自动变成御前消息。",
  "promotion.reportReceived": "收到密封军官名册",
  "promotion.reportReceivedCopy":
    "沈书吏通过独立的宫廷信使呈交证据，指出禁军任命与私人庇护网络有关。",
  "promotion.rulerFog":
    "皇帝收到了证据，却看不到呈报者的认知策略刚刚完成了晋升。",
  "promotion.knownOutcome": "已知结果",
  "promotion.documents": "御前收件箱",
  "promotion.waiting": "档案署保持沉默。",
  "promotion.waitingCopy":
    "一个持久角色可以在不引起皇帝注意的情况下存在并积累自己的历史。",
  "promotion.evidenceTitle": "宫廷档案中的证据",
  "promotion.evidenceCopy": "密封名册列出了依赖魏丞相私人网络获得任命的军官。",
  "promotion.debugBanner": "管理员视角——认知方式改变，人物身份延续",
  "promotion.identity": "持久身份",
  "promotion.office": "任职历史",
  "promotion.memories": "保留的记忆",
  "promotion.cognition": "认知层级",
  "promotion.policy": "决策策略",
  "promotion.signalTitle": "晋升信号",
  "promotion.signal.critical_information": "持有关键情报",
  "promotion.signal.high_potential_impact": "决策具有高度潜在影响",
  "promotion.decisionTitle": "已录制的 Tier 2 决策",
  "promotion.capability": "选择的能力",
  "promotion.confidence": "置信度",
  "promotion.beforeCaption":
    "晋升之前，沈书吏已经拥有身份、任职历史、动机、认知和一条日常记忆。",
  "promotion.afterCaption":
    "引擎只增加一条晋升记录并替换策略；模型收到的是同一个人物及其全部累积上下文。",
  "token.first_command_obeyed": "第一道皇命获遵",
  "token.later_command_overruled": "后一道皇命被推翻",
  "token.revision_confirmed": "改令已确认",
  "token.first_order_in_flight": "第一道命令传递中",
  "token.revision_in_flight": "改令传递中",
  "token.awaiting_response": "等待回报",
  "token.order_followed": "命令获遵",
  "token.order_overruled": "命令被相反命令压倒",
  "token.reported_complete": "回报已完成",
  "token.independent_intelligence": "独立情报",
  "token.field_report": "前线急报",
  "token.revision_report": "改令回报",
  "token.imperial-palace": "皇宫",
  "token.military-pay-office": "军饷署",
  "token.east-gate": "东门",
  "token.capital-granary": "京城粮仓",
  "token.guard-barracks": "禁军营地",
  "token.central-treasury": "中央国库",
  "token.acknowledgement": "确认回报",
  "token.administrative_return": "行政回报",
  "token.independent_audit": "独立审计",
  "token.created": "已创建",
  "token.sent": "已发出",
  "token.scheduled": "已排期",
  "token.failed": "失败",
  "token.received": "已收到",
  "token.acknowledged": "已确认",
  "token.executed": "已执行",
  "token.ignored": "已忽略",
  "token.countermanded": "已撤销",
  "token.obeyed": "服从",
  "token.not_obeyed": "未服从",
  "token.no_report": "尚无回报",
  "token.sealed_evidence_received": "已收到密封证据",
  "token.lightweight": "轻量规则",
  "token.llm": "LLM",
  "token.send_sealed_evidence_to_ruler": "向皇帝递交密封证据",
  "token.ruler": "皇帝",
  "token.chancellor": "丞相",
  "token.formal_command": "正式指挥",
  "token.legal_recognition": "法理承认",
  "token.personal_loyalty": "私人忠诚",
  "token.funding": "资金支持",
  "token.appointment": "任命关系",
  "token.informal_influence": "非正式影响",
  "token.mission_fit": "任务适配",
  "token.physical_access": "实际通行能力",
  "court.short": "嘉靖朝",
  "court.badge": "实名 · DeepSeek",
  "court.title": "嘉靖三十九年 · 改稻为桑",
  "court.intro":
    "你是嘉靖皇帝，深居西苑。外朝奏疏先经内阁票拟再送到你面前，织造局的密奏则经司礼监直达。你看到的只是送到御案上的文书；大臣们心里怎么想、私下做了什么，要到这一段结束才揭晓。每次推进都会调用真实的 DeepSeek，可能要等一两分钟。",
  "court.start": "登基",
  "court.new": "另开一局",
  "court.status.waiting": "御览中",
  "court.status.running": "朝局运转中",
  "court.status.failed": "中途受阻",
  "court.status.complete": "本段已终",
  "court.running": "大臣们各有盘算……现在是{time}。已调用模型 {calls} 次。",
  "court.desk": "今日御案",
  "court.emptyDesk": "今日御案无本章。可以发特旨，也可以直接退朝。",
  "court.kind.memorial": "奏疏",
  "court.kind.secret_memorial": "密奏（经司礼监）",
  "court.kind.report": "锦衣卫回奏",
  "court.kind.edict": "旨意",
  "court.kind.letter": "私信",
  "court.draft": "内阁票拟",
  "court.noDraft": "内阁题本，无票拟",
  "court.follow": "依拟",
  "court.custom": "改批",
  "court.hold": "留中",
  "court.vermilion": "朱批",
  "court.vermilionPlaceholder": "亲笔批语（可不写）",
  "court.disposal": "处置",
  "court.edict.acknowledge": "知道了",
  "court.edict.reject": "驳回",
  "court.edict.approve_policy": "准行改稻为桑",
  "court.edict.order_relief": "着令赈灾",
  "court.edict.order_inquiry": "派人查勘",
  "court.edict.reprimand": "申饬",
  "court.edict.arrest": "革职拿问",
  "court.county": "县",
  "court.anyCounty": "不指定",
  "court.agent": "派谁",
  "court.agent.hu": "胡宗宪",
  "court.agent.jinyiwei": "锦衣卫",
  "court.target": "何人",
  "court.special": "特旨",
  "court.addSpecial": "拟一道特旨",
  "court.remove": "删去",
  "court.submit": "御览毕",
  "court.retry": "重试（已下的旨意不变）",
  "court.archive": "已阅文书",
  "court.edicts": "所发旨意",
  "court.to": "发往 {names}",
  "court.rescript.hold": "留中",
  "court.rescript.follow_draft": "依拟",
  "court.rescript.custom": "改批",
  "court.finished": "这一段统治结束了。",
  "court.reveal": "揭开内幕",
  "court.replay": "校验记录回放（不调用 API）",
  "court.verified": "回放与存档一致，未调用模型。",
  "court.review.title": "局终复盘 · 所想 / 所言 / 所为 / 实情",
  "court.review.truth": "实情",
  "court.review.thought": "所想",
  "court.review.word": "所言",
  "court.review.deed": "所为",
  "court.review.nothing": "什么也没做。",
  "court.review.silent": "未发文书。",
  "court.review.rejected": "未能施行",
  "court.review.gaps": "超出现有能力的意图",
  "court.review.final": "被拿问后",
  "court.review.evidence":
    "{county}大堤系人为掘开（{by}所为）；查出者：{found}",
  "court.review.nobody": "无人",
  "court.review.calls": "模型调用",
  "court.summary":
    "改桑 {converted} / {target} 万亩，其中低价归入商人名下 {annexed} 万亩；死亡 {deaths} 人；民变 {riots} 次。",
  "court.table.county": "县",
  "court.table.dike": "大堤",
  "court.table.flooded": "淹田",
  "court.table.mulberry": "改桑",
  "court.table.annexed": "兼并",
  "court.table.homeless": "灾民",
  "court.table.deaths": "死亡",
  "court.table.riots": "民变",
  "court.table.relief": "赈粮",
  "court.dike.intact": "无恙",
  "court.dike.flood": "汛水冲决",
  "court.dike.sabotage": "人为掘开",
  "court.cap.buy_land": "收买田亩",
  "court.cap.relief_granary": "开官仓赈灾",
  "court.cap.relief_military": "拨军粮赈灾",
  "court.cap.relief_merchant": "以粮换田",
  "court.cap.breach_dike": "掘堤",
  "court.cap.repair_dike": "修堤",
  "court.cap.suppress_unrest": "弹压",
  "court.cap.inspect_county": "查勘",
  "court.action.started": "进行中",
  "court.action.succeeded": "办成",
  "court.action.failed": "未成",
  "court.action.impossible": "办不到",
};
